# Your Solution

version: '3'
services:

  deakin-book_catalog:
    image: deakin-book_catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: deakin-book_catalog
    ports:
     - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://part5:UmveLzdhXrPJrlvfZ95a2i0vIZxwohwR@dpg-crk2ksbtq21c73a99jhg-a.oregon-postgres.render.com/part_5
    restart: "no"

  deakin-inventory:
    image: deakin-inventory
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: deakin-inventory
    ports:
     - "8001:8000"
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://part5:UmveLzdhXrPJrlvfZ95a2i0vIZxwohwR@dpg-crk2ksbtq21c73a99jhg-a.oregon-postgres.render.com/part_5
    restart: "no"