
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deakin-book-catalog
  labels:
    app: deakin-book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deakin-book-catalog
  template:
    metadata:
      labels:
        app: deakin-book-catalog
    spec:
      containers:
      - name: deakin-book-catalog
        image: $CONTAINER_REGISTRY/deakin-book-catalog:$VERSION
        
        imagePullPolicy: IfNotPresent 
        env:
        - name: PORT
          value: "4000"
        - name: DATABASE_URL
          value: $DATABASE_URL
          
---
apiVersion: v1
kind: Service
metadata:
  name: deakin-book-catalog
spec:
  selector:
    app: deakin-book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 4000