
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deakin-inventory
  labels:
    app: deakin-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deakin-inventory
  template:
    metadata:
      labels:
        app: deakin-inventory
    spec:
      containers:
      - name: deakin-inventory
        image: $CONTAINER_REGISTRY/deakin-inventory:$VERSION
        
        imagePullPolicy: IfNotPresent 
        env:
        - name: PORT
          value: "5000"
        - name: DATABASE_URL
          value: $DATABASE_URL
          
---
apiVersion: v1
kind: Service
metadata:
  name: deakin-inventory
spec:
  selector:
    app: deakin-inventory
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 5000