
name: Deploy Deakin Inventory (inventory_management)

on:
 
  push: 
    branches:
      - main
    paths:
      - inventory_management/**

 
  workflow_dispatch: 

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}
      DATABASE_URL: ${{ secrets.DATABASE_URL  }}
      NAME: deakin-inventory
      DIRECTORY: inventory_management

    steps:
      
     
      - uses: actions/checkout@v4

      - name: Set up permissions for build script
        run: chmod +x ./scripts/build-image.sh

      - name: Set up permissions for push-image script
        run: chmod +x ./scripts/push-image.sh

      - name: Set up permissions for deploy script
        run: chmod +x ./scripts/deploy.sh

      - name: Build
        run: ./scripts/build-image.sh

      
      - name: Publish
        run: ./scripts/push-image.sh

      
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.24.2
      
      
      - name: Deploy
        run: ./scripts/deploy.sh